In [16]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("tomato_jan_2024.csv", header=None, names=["date", "arrivals", "variety", "min_price", "max_price", "modal_price"])
df.head(10)

,date,arrivals,variety,min_price,max_price,modal_price
0,Date Wise Prices for Specified Commodity on Ja...,NaN,NaN,NaN,NaN,NaN
1,"Commodity : Tomato, State : Andhra Pradesh",NaN,NaN,NaN,NaN,NaN
2,Arrival Date,Arrivals (Metric Tonnes),Variety,Minimum Price (Rs./Quintal),Maximum Price (Rs./Quintal),Modal Price (Rs./Quintal)
3,Market Name : Kalikiri APMC,NaN,NaN,NaN,NaN,NaN
4,01/01/2024,9.4,Local,1000.0,2000.0,1500.0
5,02/01/2024,7.0,Local,1000.0,2300.0,1700.0
6,03/01/2024,8.3,Local,1200.0,2660.0,2000.0
7,04/01/2024,8.2,Local,900.0,2000.0,1600.0
8,05/01/2024,7.0,Local,1000.0,2300.0,1700.0
9,07/01/2024,9.0,Local,1000.0,2300.0,1700.0

In [5]:
import pandas as pd

df = pd.read_csv("tomato_jan_2024.csv", header=None, names=["date", "arrivals", "variety", "min_price", "max_price", "modal_price"])

df["date"] = pd.to_datetime(df["date"], dayfirst=True, errors="coerce")

df["month"] = df["date"].dt.month

df = df.dropna(subset=["date"])

print(df.shape)
df.head()

(693, 7)

C:\Users\saran\AppData\Local\Temp\ipykernel_17724\417150674.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["date"] = pd.to_datetime(df["date"], dayfirst=True, errors="coerce")

        date arrivals variety min_price max_price modal_price  month
4 2024-01-01      9.4   Local    1000.0    2000.0      1500.0    1.0
5 2024-01-02      7.0   Local    1000.0    2300.0      1700.0    1.0
6 2024-01-03      8.3   Local    1200.0    2660.0      2000.0    1.0
7 2024-01-04      8.2   Local     900.0    2000.0      1600.0    1.0
8 2024-01-05      7.0   Local    1000.0    2300.0      1700.0    1.0

In [ ]:
df["modal_price"] = pd.to_numeric(df["modal_price"], errors="coerce")

monthly_avg = df.groupby("month")["modal_price"].mean()
print(monthly_avg)

TypeError: agg function failed [how->mean,dtype->object]